name: bandits-reco
channels:
  - anaconda
  - defaults
dependencies:
  - notebook=5.6.0
  - matplotlib=2.2.3
  - numpy=1.15.1
  - python=3.7.1
  - pandas=0.23.4
  - scipy=1.1.0
  - scikit-learn=0.20.1